title: UI/UX Developer - Neil Akhmetov
url: "https://neelts.github.io"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
skin: "dark"
plugins:
  - jekyll-include-cache
  - jekyll-titles-from-headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false